"""create_initial_table

Revision ID: 04013f6ddfc1
Revises: 98c7d08d059f
Create Date: 2026-04-23 08:01:15.567274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04013f6ddfc1'
down_revision: Union[str, Sequence[str], None] = '98c7d08d059f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('predicted_label', sa.String(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_table('user_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('mq_lag_24h', sa.Float(), nullable=True),
    sa.Column('mq_mean_24h', sa.Float(), nullable=True),
    sa.Column('is_weekend', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_features_id'), 'user_features', ['id'], unique=False)
    op.add_column('sensor_logs', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('sensor_logs_user_id_fkey'), 'sensor_logs', type_='foreignkey')
    op.create_foreign_key(None, 'sensor_logs', 'devices', ['device_id'], ['id'])
    op.drop_column('sensor_logs', 'user_id')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.add_column('sensor_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sensor_logs', type_='foreignkey')
    op.create_foreign_key(op.f('sensor_logs_user_id_fkey'), 'sensor_logs', 'users', ['user_id'], ['id'])
    op.drop_column('sensor_logs', 'device_id')
    op.drop_index(op.f('ix_user_features_id'), table_name='user_features')
    op.drop_table('user_features')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
