"""create table for log testing

Revision ID: 13313e352931
Revises: eeb062ee9260
Create Date: 2026-07-01 15:21:27.341237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13313e352931'
down_revision: Union[str, Sequence[str], None] = 'eeb062ee9260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_testing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('t_sensor', sa.Float(), nullable=True),
    sa.Column('t_send', sa.Float(), nullable=True),
    sa.Column('t_ack', sa.Float(), nullable=True),
    sa.Column('t_actuator', sa.Float(), nullable=True),
    sa.Column('rtt_us', sa.Float(), nullable=True),
    sa.Column('e2e_us', sa.Float(), nullable=True),
    sa.Column('payload_bits', sa.Float(), nullable=True),
    sa.Column('payload_length', sa.Float(), nullable=True),
    sa.Column('total_heap', sa.Float(), nullable=True),
    sa.Column('free_heap', sa.Float(), nullable=True),
    sa.Column('ram_load_pct', sa.Float(), nullable=True),
    sa.Column('voltage_v', sa.Float(), nullable=True),
    sa.Column('current_ma', sa.Float(), nullable=True),
    sa.Column('power_mw', sa.Float(), nullable=True),
    sa.Column('energy_mj', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['classification.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_testing_id'), 'log_testing', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_testing_id'), table_name='log_testing')
    op.drop_table('log_testing')
    # ### end Alembic commands ###
