"""update structure to final erd

Revision ID: 34af93574e1b
Revises: e0aed3320054
Create Date: 2026-06-13 07:35:03.939646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34af93574e1b'
down_revision: Union[str, Sequence[str], None] = 'e0aed3320054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_dht22',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_dht22_id'), 'sensor_dht22', ['id'], unique=False)
    op.create_table('sensor_mq135',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('mq135', sa.Float(), nullable=True),
    sa.Column('ppm_nh3', sa.Float(), nullable=True),
    sa.Column('ppm_co', sa.Float(), nullable=True),
    sa.Column('ppm_co2', sa.Float(), nullable=True),
    sa.Column('ppm_acetone', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_mq135_id'), 'sensor_mq135', ['id'], unique=False)
    op.create_table('conclusion_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_mq135_id', sa.Integer(), nullable=True),
    sa.Column('sensor_dht22_id', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Time(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_dht22_id'], ['sensor_dht22.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_mq135_id'], ['sensor_mq135.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conclusion_feature_id'), 'conclusion_feature', ['id'], unique=False)
    op.create_table('classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conclusion_feature_id', sa.Integer(), nullable=True),
    sa.Column('label_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conclusion_feature_id'], ['conclusion_feature.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_id'), 'classification', ['id'], unique=False)
    op.drop_index(op.f('ix_user_features_id'), table_name='user_features')
    op.drop_table('user_features')
    op.drop_index(op.f('ix_sensor_logs_id'), table_name='sensor_logs')
    op.drop_table('sensor_logs')
    op.add_column('devices', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('devices_user_id_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('predictions', sa.Column('conclusion_feature_id', sa.Integer(), nullable=True))
    op.add_column('predictions', sa.Column('label_status', sa.String(), nullable=True))
    op.add_column('predictions', sa.Column('target_time', sa.Time(), nullable=True))
    op.add_column('predictions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('predictions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('predictions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('predictions_user_id_fkey'), 'predictions', type_='foreignkey')
    op.drop_constraint(op.f('predictions_device_id_fkey'), 'predictions', type_='foreignkey')
    op.create_foreign_key(None, 'predictions', 'conclusion_feature', ['conclusion_feature_id'], ['id'], ondelete='CASCADE')
    op.drop_column('predictions', 'user_id')
    op.drop_column('predictions', 'predicted_label')
    op.drop_column('predictions', 'device_id')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('predictions', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('predicted_label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.create_foreign_key(op.f('predictions_device_id_fkey'), 'predictions', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(op.f('predictions_user_id_fkey'), 'predictions', 'users', ['user_id'], ['id'])
    op.drop_column('predictions', 'deleted_at')
    op.drop_column('predictions', 'updated_at')
    op.drop_column('predictions', 'created_at')
    op.drop_column('predictions', 'target_time')
    op.drop_column('predictions', 'label_status')
    op.drop_column('predictions', 'conclusion_feature_id')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_user_id_fkey'), 'devices', 'users', ['user_id'], ['id'])
    op.drop_column('devices', 'deleted_at')
    op.drop_column('devices', 'updated_at')
    op.drop_column('devices', 'created_at')
    op.create_table('sensor_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mq_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('sensor_logs_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sensor_logs_pkey'))
    )
    op.create_index(op.f('ix_sensor_logs_id'), 'sensor_logs', ['id'], unique=False)
    op.create_table('user_features',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mq_lag_24h', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mq_mean_24h', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_weekend', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('user_features_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_features_pkey'))
    )
    op.create_index(op.f('ix_user_features_id'), 'user_features', ['id'], unique=False)
    op.drop_index(op.f('ix_classification_id'), table_name='classification')
    op.drop_table('classification')
    op.drop_index(op.f('ix_conclusion_feature_id'), table_name='conclusion_feature')
    op.drop_table('conclusion_feature')
    op.drop_index(op.f('ix_sensor_mq135_id'), table_name='sensor_mq135')
    op.drop_table('sensor_mq135')
    op.drop_index(op.f('ix_sensor_dht22_id'), table_name='sensor_dht22')
    op.drop_table('sensor_dht22')
    # ### end Alembic commands ###
