"""generate unique device name

Revision ID: 8ee56d93f7c4
Revises: 1db1ed1721f5
Create Date: 2026-06-16 10:23:47.900333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee56d93f7c4'
down_revision: Union[str, Sequence[str], None] = '1db1ed1721f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_devices_device_name'), 'devices', ['device_name'], unique=True)
    op.create_unique_constraint(None, 'devices', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_index(op.f('ix_devices_device_name'), table_name='devices')
    # ### end Alembic commands ###
