"""add device_token

Revision ID: eeb062ee9260
Revises: ca9e21703ae5
Create Date: 2026-06-25 15:09:32.306719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb062ee9260'
down_revision: Union[str, Sequence[str], None] = 'ca9e21703ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_devices_device_token'), 'devices', ['device_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_device_token'), table_name='devices')
    op.drop_column('devices', 'device_token')
    # ### end Alembic commands ###
